sudo: required
dist: trusty
language: cpp
compiler:
- gcc
before_install:
# for gcc with C++11 support
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
install:
# install GTest and GMock
- sudo apt-get -qq install libgtest-dev
- "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- sudo apt-get -qq install google-mock
- "cd /usr/src/gmock && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- sudo apt-get -qq install libtest-simple-perl
- sudo apt-get -qq install libtest-harness-perl
- sudo apt-get -qq install libcrypt-ssleay-perl
- sudo apt-get -qq install libsoap-lite-perl
- sudo apt-get -qq install libtest-pod-coverage-perl
# install latest LCOV (1.9 was failing)
- cd ${TRAVIS_BUILD_DIR}
- g++ --version
before_script:
- cd ${TRAVIS_BUILD_DIR}
# init coverage to 0 (optional)
- lcov --directory . --zerocounters
script:
- cd ${TRAVIS_BUILD_DIR}
# Check that this works this way
- perl Makefile.PL
- make
- TEST_POD=1 make test
